import type { AgentCapability } from "./types";

const jsonObject = { type: "object", additionalProperties: true };
const jsonArray = { type: "array", items: jsonObject };

export const AGENT_CAPABILITIES: AgentCapability[] = [
  {
    name: "cashpile.briefing.generate",
    title: "Generate Cashpile briefing",
    description: "Generate a concise cross-module financial briefing using Books, Trades, and Pulse data.",
    module: "cashpile",
    kind: "read",
    requiredScopes: ["books:read", "trades:read", "pulse:read"],
    requiresConfirmation: false,
    inputSchema: { type: "object", properties: {}, additionalProperties: false },
    outputSchema: { type: "object", properties: { briefing: { type: "string" } } },
    rateLimit: { requests: 30, windowSeconds: 60 },
  },
  {
    name: "books.transactions.list",
    title: "List Books transactions",
    description: "List the user's Books transactions with optional date, account, category, and pagination filters.",
    module: "books",
    kind: "read",
    requiredScopes: ["books:read"],
    requiresConfirmation: false,
    inputSchema: {
      type: "object",
      properties: {
        dateFrom: { type: "string", format: "date" },
        dateTo: { type: "string", format: "date" },
        accountId: { type: "string" },
        categoryId: { type: "string" },
        limit: { type: "integer", minimum: 1, maximum: 100 },
        offset: { type: "integer", minimum: 0 },
      },
      additionalProperties: false,
    },
    outputSchema: { type: "object", properties: { transactions: jsonArray, count: { type: "integer" } } },
    rateLimit: { requests: 120, windowSeconds: 60 },
  },
  {
    name: "books.accounts.list",
    title: "List Books accounts",
    description: "List the user's linked/manual financial accounts in Books.",
    module: "books",
    kind: "read",
    requiredScopes: ["books:read"],
    requiresConfirmation: false,
    inputSchema: { type: "object", properties: { taxEntityId: { type: "string" } }, additionalProperties: false },
    outputSchema: { type: "object", properties: { accounts: jsonArray } },
    rateLimit: { requests: 120, windowSeconds: 60 },
  },
  {
    name: "books.categories.list",
    title: "List Books categories",
    description: "List the user's Books transaction categories.",
    module: "books",
    kind: "read",
    requiredScopes: ["books:read"],
    requiresConfirmation: false,
    inputSchema: { type: "object", properties: {}, additionalProperties: false },
    outputSchema: { type: "object", properties: { categories: jsonArray } },
    rateLimit: { requests: 120, windowSeconds: 60 },
  },
  {
    name: "books.transactions.categorize",
    title: "Categorize Books transactions",
    description: "Assign a category to one or more Books transactions. Requires a server-side confirmation token.",
    module: "books",
    kind: "write",
    requiredScopes: ["books:write"],
    requiresConfirmation: true,
    inputSchema: {
      type: "object",
      required: ["transactionIds", "categoryId"],
      properties: {
        transactionIds: { type: "array", items: { type: "string" }, minItems: 1, maxItems: 200 },
        categoryId: { type: "string" },
      },
      additionalProperties: false,
    },
    outputSchema: { type: "object", properties: { updated: { type: "integer" } } },
    rateLimit: { requests: 30, windowSeconds: 60 },
  },
  {
    name: "tax.report.generate",
    title: "Generate tax report",
    description: "Return tax transaction report rows and summary totals for a tax entity and year.",
    module: "tax",
    kind: "export",
    requiredScopes: ["tax:read"],
    requiresConfirmation: false,
    inputSchema: {
      type: "object",
      required: ["taxEntityId"],
      properties: { taxEntityId: { type: "string" }, year: { type: "integer" } },
      additionalProperties: false,
    },
    outputSchema: { type: "object", properties: { summary: jsonObject, transactions: jsonArray } },
    rateLimit: { requests: 30, windowSeconds: 60 },
  },
  {
    name: "trades.snapshot.get",
    title: "Get Trades snapshot",
    description: "Return active prop trading accounts, total P&L, drawdown risk, and recent closed trades.",
    module: "trades",
    kind: "read",
    requiredScopes: ["trades:read"],
    requiresConfirmation: false,
    inputSchema: { type: "object", properties: {}, additionalProperties: false },
    outputSchema: { type: "object", additionalProperties: true },
    rateLimit: { requests: 60, windowSeconds: 60 },
  },
  {
    name: "pulse.events.list",
    title: "List Pulse events",
    description: "List recent Pulse macro/financial events with optional instrument filtering.",
    module: "pulse",
    kind: "read",
    requiredScopes: ["pulse:read"],
    requiresConfirmation: false,
    inputSchema: {
      type: "object",
      properties: { instruments: { type: "array", items: { type: "string" } }, limit: { type: "integer", minimum: 1, maximum: 50 } },
      additionalProperties: false,
    },
    outputSchema: { type: "object", properties: { events: jsonArray } },
    rateLimit: { requests: 120, windowSeconds: 60 },
  },
  {
    name: "pulse.alerts.list",
    title: "List Pulse alerts",
    description: "List the user's Pulse alerts, unread-only by default.",
    module: "pulse",
    kind: "read",
    requiredScopes: ["pulse:read"],
    requiresConfirmation: false,
    inputSchema: { type: "object", properties: { unreadOnly: { type: "boolean" } }, additionalProperties: false },
    outputSchema: { type: "object", properties: { alerts: jsonArray, unreadCount: { type: "integer" } } },
    rateLimit: { requests: 120, windowSeconds: 60 },
  },
];

export function getAgentCapability(name: string) {
  return AGENT_CAPABILITIES.find((capability) => capability.name === name) ?? null;
}
