import type { AgentCapability } from "./types";

const jsonObject = { type: "object", additionalProperties: true };
const jsonArray = { type: "array", items: jsonObject };

export const AGENT_CAPABILITIES: AgentCapability[] = [

  {
    name: "cashflow.snapshot.get",
    title: "Get cash-flow snapshot",
    description: "Return spendable cash, inferred recurring income/bills, projected low balance, buffer, and safe-to-spend amount.",
    module: "cashflow",
    kind: "read",
    requiredScopes: ["books:read"],
    requiresConfirmation: false,
    inputSchema: {
      type: "object",
      properties: { horizonDays: { type: "integer", minimum: 7, maximum: 90 } },
      additionalProperties: false,
    },
    outputSchema: { type: "object", additionalProperties: true },
    rateLimit: { requests: 60, windowSeconds: 60 },
  },
  {
    name: "cashflow.affordability.check",
    title: "Check affordability",
    description: "Check whether a planned purchase is affordable using projected cash flow and buffer policy.",
    module: "cashflow",
    kind: "read",
    requiredScopes: ["books:read"],
    requiresConfirmation: false,
    inputSchema: {
      type: "object",
      required: ["amount"],
      properties: {
        amount: { type: "number", minimum: 0.01 },
        description: { type: "string" },
        date: { type: "string", format: "date" },
        horizonDays: { type: "integer", minimum: 7, maximum: 90 },
      },
      additionalProperties: false,
    },
    outputSchema: { type: "object", additionalProperties: true },
    rateLimit: { requests: 60, windowSeconds: 60 },
  },
  {
    name: "cashflow.recurring_items.list",
    title: "List recurring cash-flow items",
    description: "List inferred recurring income and bills used by Cash Flow Copilot.",
    module: "cashflow",
    kind: "read",
    requiredScopes: ["books:read"],
    requiresConfirmation: false,
    inputSchema: { type: "object", properties: {}, additionalProperties: false },
    outputSchema: { type: "object", properties: { recurringItems: jsonArray } },
    rateLimit: { requests: 60, windowSeconds: 60 },
  },
  {
    name: "cashpile.briefing.generate",
    title: "Generate Cashpile briefing",
    description: "Generate a concise personal-finance briefing using Books, cash-flow, and tax data.",
    module: "cashpile",
    kind: "read",
    requiredScopes: ["books:read"],
    requiresConfirmation: false,
    inputSchema: { type: "object", properties: {}, additionalProperties: false },
    outputSchema: { type: "object", properties: { briefing: { type: "string" } } },
    rateLimit: { requests: 30, windowSeconds: 60 },
  },
  {
    name: "books.transactions.list",
    title: "List Books transactions",
    description: "List the user's Books transactions with optional date, account, category, and pagination filters.",
    module: "books",
    kind: "read",
    requiredScopes: ["books:read"],
    requiresConfirmation: false,
    inputSchema: {
      type: "object",
      properties: {
        dateFrom: { type: "string", format: "date" },
        dateTo: { type: "string", format: "date" },
        accountId: { type: "string" },
        categoryId: { type: "integer" },
        limit: { type: "integer", minimum: 1, maximum: 100 },
        offset: { type: "integer", minimum: 0 },
      },
      additionalProperties: false,
    },
    outputSchema: { type: "object", properties: { transactions: jsonArray, count: { type: "integer" } } },
    rateLimit: { requests: 120, windowSeconds: 60 },
  },
  {
    name: "books.accounts.list",
    title: "List Books accounts",
    description: "List the user's linked/manual financial accounts in Books.",
    module: "books",
    kind: "read",
    requiredScopes: ["books:read"],
    requiresConfirmation: false,
    inputSchema: { type: "object", properties: { taxEntityId: { type: "string" } }, additionalProperties: false },
    outputSchema: { type: "object", properties: { accounts: jsonArray } },
    rateLimit: { requests: 120, windowSeconds: 60 },
  },
  {
    name: "books.categories.list",
    title: "List Books categories",
    description: "List the user's Books transaction categories.",
    module: "books",
    kind: "read",
    requiredScopes: ["books:read"],
    requiresConfirmation: false,
    inputSchema: { type: "object", properties: {}, additionalProperties: false },
    outputSchema: { type: "object", properties: { categories: jsonArray } },
    rateLimit: { requests: 120, windowSeconds: 60 },
  },
  {
    name: "books.transactions.categorize",
    title: "Categorize Books transactions",
    description: "Assign a category to one or more Books transactions. Requires a server-side confirmation token.",
    module: "books",
    kind: "write",
    requiredScopes: ["books:write"],
    requiresConfirmation: true,
    inputSchema: {
      type: "object",
      required: ["transactionIds", "categoryId"],
      properties: {
        transactionIds: { type: "array", items: { type: "string" }, minItems: 1, maxItems: 200 },
        categoryId: { type: "integer" },
      },
      additionalProperties: false,
    },
    outputSchema: { type: "object", properties: { updated: { type: "integer" } } },
    rateLimit: { requests: 30, windowSeconds: 60 },
  },
  {
    name: "tax.report.generate",
    title: "Generate tax report",
    description: "Return tax transaction report rows and summary totals for a tax entity and year.",
    module: "tax",
    kind: "export",
    requiredScopes: ["tax:read"],
    requiresConfirmation: false,
    inputSchema: {
      type: "object",
      required: ["taxEntityId"],
      properties: { taxEntityId: { type: "string" }, year: { type: "integer" } },
      additionalProperties: false,
    },
    outputSchema: { type: "object", properties: { summary: jsonObject, transactions: jsonArray } },
    rateLimit: { requests: 30, windowSeconds: 60 },
  },
];

export function getAgentCapability(name: string) {
  return AGENT_CAPABILITIES.find((capability) => capability.name === name) ?? null;
}
